# Generated by Django 5.2.4 on 2025-07-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image'),
        ),
    ]
